default_agent: customer_support_agent
agents:
  customer_support_agent:
    name: customer_support_agent
    entrypoint: /home/ec2-user/projects/poke-platform/agentcore_e2e/runtime_entrypoint.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: arn:aws:iam::878817878019:role/CustomerSupportAssistantBedrockAgentCoreRole-us-east-2
      execution_role_auto_create: false
      account: '878817878019'
      region: us-east-2
      ecr_repository: 878817878019.dkr.ecr.us-east-2.amazonaws.com/bedrock-agentcore-customer_support_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: customer_support_agent-EVm7f6AcLm
      agent_arn: arn:aws:bedrock-agentcore:us-east-2:878817878019:runtime/customer_support_agent-EVm7f6AcLm
      agent_session_id: 75318b19-af32-4bd5-b423-98abb7ae754f
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration:
      customJWTAuthorizer:
        allowedClients:
        - 3r3ro57glqqvqpaiqdvdj00552
        discoveryUrl: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_w6oTTpRnI/.well-known/openid-configuration
    request_header_configuration:
      requestHeaderAllowlist:
      - Authorization
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
